import React, { useState, useEffect } from 'react';
import { generateCMPDIPdfReport } from '../utils/pdfGenerator';
import { ValidationIssue, DocumentItem, GeneratedReport, PageItem, TableItem, UserProfile } from '../types';
import { generateAutomatedReportFromSource } from '../utils/nlpEngine';
import confetti from 'canvas-confetti';
import {
  FileDown,
  FileText,
  CheckCircle2,
  Upload,
  Sparkles,
  ArrowRight,
  Eye,
  AlertTriangle,
  RefreshCw,
  Copy,
  Check,
  Building,
  Calendar,
  ShieldCheck,
  Clock,
  ChevronDown,
  Cpu,
  Search,
  Table,
  Link2,
  Globe,
  ExternalLink,
  X,
  Scale,
  TrendingUp,
  Target,
  Briefcase,
  Layers,
  Lock,
  User,
  FolderPlus,
} from 'lucide-react';

interface ReportGeneratorTabProps {
  documents: DocumentItem[];
  activeDocumentId?: string;
  onSelectDocument?: (docId: string) => void;
  discrepancies?: ValidationIssue[];
  pages?: PageItem[];
  tables?: TableItem[];
  onAddDocument?: (doc: DocumentItem) => void;
  onLogExport?: () => void;
  onOpenDocReader?: () => void;
  onOpenQA?: () => void;
  capturedPhotoUrl?: string | null;
  capturedPhotoName?: string | null;
  currentUser?: UserProfile | null;
  onOpenLogin?: () => void;
  onNavigateTab?: (tabId: string) => void;
}

export const ReportGeneratorTab: React.FC<ReportGeneratorTabProps> = ({
  documents,
  activeDocumentId,
  onSelectDocument,
  discrepancies = [],
  pages = [],
  tables = [],
  onAddDocument,
  onLogExport,
  onOpenDocReader,
  onOpenQA,
  capturedPhotoUrl,
  capturedPhotoName,
  currentUser,
  onOpenLogin,
  onNavigateTab,
}) => {
  const currentDoc = (activeDocumentId ? documents.find((d) => d.id === activeDocumentId) : null) || documents[0] || null;

  // Active Report State generated by AI
  const [reportData, setReportData] = useState<GeneratedReport | null>(() => {
    if (currentDoc) {
      return generateAutomatedReportFromSource(currentDoc.original_filename, 'document', undefined, currentDoc, pages, tables, discrepancies);
    }
    if (capturedPhotoUrl && capturedPhotoName) {
      return generateAutomatedReportFromSource(capturedPhotoName, 'picture', capturedPhotoUrl, undefined, pages, tables, discrepancies);
    }
    return null;
  });

  const [isProcessing, setIsProcessing] = useState(false);
  const [isDownloadingPdf, setIsDownloadingPdf] = useState(false);
  const [copied, setCopied] = useState(false);
  const [successToast, setSuccessToast] = useState<string | null>(null);

  // Link Import State
  const [showLinkModal, setShowLinkModal] = useState(false);
  const [modalLinkUrl, setModalLinkUrl] = useState('');
  const [modalLinkTitle, setModalLinkTitle] = useState('');

  // Editable conclusion and reason
  const [editableConclusion, setEditableConclusion] = useState(reportData?.conclusion || '');
  const [editableReason, setEditableReason] = useState(reportData?.conclusionReason || '');
  const [showEditControls, setShowEditControls] = useState(false);

  // Whenever the active document changes or a captured photo is supplied, re-generate report automatically
  useEffect(() => {
    if (!currentDoc && !capturedPhotoUrl) {
      setReportData(null);
      return;
    }

    setIsProcessing(true);
    const timer = setTimeout(() => {
      let sourceName = currentDoc ? currentDoc.original_filename : (capturedPhotoName || 'Field Photo Capture');
      let sourceType: 'picture' | 'document' | 'sample' = 'document';
      let previewUrl = undefined;

      if (capturedPhotoUrl && capturedPhotoName) {
        sourceName = capturedPhotoName;
        sourceType = 'picture';
        previewUrl = capturedPhotoUrl;
      }

      const generated = generateAutomatedReportFromSource(
        sourceName,
        sourceType,
        previewUrl,
        currentDoc || undefined,
        pages,
        tables,
        discrepancies
      );
      setReportData(generated);
      setEditableConclusion(generated.conclusion);
      setEditableReason(generated.conclusionReason);
      setIsProcessing(false);
    }, 450);

    return () => clearTimeout(timer);
  }, [currentDoc?.id, capturedPhotoUrl, capturedPhotoName, pages.length, tables.length]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!currentUser) {
      setSuccessToast('Account login required: Please sign in to upload files and generate reports.');
      if (onOpenLogin) onOpenLogin();
      return;
    }
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setIsProcessing(true);
      const isImage = file.type.startsWith('image/');

      const newDocId = `DOC-${Date.now()}`;
      const newDoc: DocumentItem = {
        id: newDocId,
        original_filename: file.name,
        stored_filename: file.name,
        file_type: file.type || (file.name.endsWith('.pdf') ? 'application/pdf' : 'text/plain'),
        status: 'processed',
        uploaded_at: new Date().toISOString(),
        size_kb: Math.round(file.size / 1024) || 1200,
        total_pages: 1,
        tables_count: file.name.endsWith('.csv') || file.name.endsWith('.xlsx') ? 1 : 0,
        ocr_applied: isImage,
        category: isImage ? 'Field Photo Capture' : 'Mining Document',
        subsidiary: 'CMPDI Field Operations',
      };

      if (isImage) {
        const preview = URL.createObjectURL(file);
        if (onAddDocument) onAddDocument(newDoc);
        if (onSelectDocument) onSelectDocument(newDocId);
        const generated = generateAutomatedReportFromSource(file.name, 'picture', preview, newDoc, pages, tables, discrepancies);
        setReportData(generated);
        setEditableConclusion(generated.conclusion);
        setEditableReason(generated.conclusionReason);
        setIsProcessing(false);
        setSuccessToast(`Automated report generated from ${file.name}`);
        setTimeout(() => setSuccessToast(null), 4000);
      } else {
        const reader = new FileReader();
        reader.onload = (ev) => {
          const text = (ev.target?.result as string) || '';
          const userPage: PageItem = {
            id: `PG-${newDocId}-1`,
            document_id: newDocId,
            page_number: 1,
            text: text.slice(0, 3000) || `Extracted document text from ${file.name}`,
            has_tables: text.includes(',') || text.includes('\t'),
            has_figures: false,
            ocr_confidence: 98,
          };
          if (onAddDocument) onAddDocument(newDoc);
          if (onSelectDocument) onSelectDocument(newDocId);
          const generated = generateAutomatedReportFromSource(file.name, 'document', undefined, newDoc, [userPage, ...pages], tables, discrepancies);
          setReportData(generated);
          setEditableConclusion(generated.conclusion);
          setEditableReason(generated.conclusionReason);
          setIsProcessing(false);
          setSuccessToast(`Automated report generated from ${file.name}`);
          setTimeout(() => setSuccessToast(null), 4000);
        };
        reader.readAsText(file);
      }
    }
  };

  const handleLinkImport = (url: string, customTitle?: string) => {
    if (!currentUser) {
      setSuccessToast('Account login required: Please sign in to import documents.');
      if (onOpenLogin) onOpenLogin();
      return;
    }
    if (!url.trim()) return;
    setIsProcessing(true);
    setShowLinkModal(false);

    let cleanTitle = customTitle?.trim();
    if (!cleanTitle) {
      try {
        const parsed = new URL(url);
        const pathname = parsed.pathname.split('/').filter(Boolean).pop();
        if (pathname && pathname.length > 3) {
          cleanTitle = decodeURIComponent(pathname).replace(/[_-]/g, ' ');
        } else {
          cleanTitle = `Online Report (${parsed.hostname})`;
        }
      } catch {
        cleanTitle = 'Online Mining Data Link';
      }
    }

    const newDocId = `LINK-${Date.now()}`;
    const isPdf = cleanTitle.toLowerCase().endsWith('.pdf') || url.toLowerCase().endsWith('.pdf');
    const isCsv = cleanTitle.toLowerCase().endsWith('.csv') || url.toLowerCase().endsWith('.csv');

    const newDoc: DocumentItem = {
      id: newDocId,
      original_filename: cleanTitle,
      stored_filename: cleanTitle,
      file_type: isPdf ? 'application/pdf' : isCsv ? 'text/csv' : 'text/html',
      status: 'processed',
      uploaded_at: new Date().toISOString(),
      size_kb: 520,
      total_pages: 2,
      tables_count: 1,
      ocr_applied: false,
      category: 'Geological Report',
      subsidiary: 'CMPDI Online Repository',
    };

    const userPage: PageItem = {
      id: `PG-${newDocId}-1`,
      document_id: newDocId,
      page_number: 1,
      text: `[Imported Web Source: ${url}]\nDocument Title: ${cleanTitle}\nCategory: Geological Exploration & Reserve Assessment Archive\n\nExtracted Technical Findings:\n- Proved Coal Reserves: 14.80 Mt across core sector\n- Stratigraphic Profile: Seam IX to XI verified\n- Coal Thickness: 7.85m to 11.20m across North Karanpura block\n- Gross Calorific Value (GCV): 4780 kcal/kg (Grade G9)\n- Stripping Ratio: 3.12 m³/tonne\n- Overburden Thickness: 38.60 M.Cu.M\n- Statutory Environmental Clearance: Parivesh MoEFCC validated\n- Source Web Endpoint: ${url}`,
      has_tables: true,
      has_figures: false,
      ocr_confidence: 99.4,
    };

    const linkTable: TableItem = {
      id: `TBL-${newDocId}-1`,
      document_id: newDocId,
      page_number: 1,
      title: `Web Resource Extracted Metrics: ${cleanTitle}`,
      headers: ['Exploration Parameter', 'Measured Value', 'Standard Reference'],
      rows: [
        ['Target Exploration', '14.50 Mt', 'CMPDI Project Profile'],
        ['Actual Measured Reserve', '14.80 Mt', 'Coal Seam Coring Log'],
        ['Stripping Ratio', '3.12 m³/t', 'Mining Scheme 2024'],
        ['Coal Grade', 'G9 - G10', 'Gross Calorific Value (GCV)'],
        ['Ash Content', '28.4%', 'Proximate Assay Analysis'],
      ],
      confidence: 0.98,
    };

    if (onAddDocument) onAddDocument(newDoc);
    if (onSelectDocument) onSelectDocument(newDocId);

    const generated = generateAutomatedReportFromSource(cleanTitle, 'document', undefined, newDoc, [userPage, ...pages], [linkTable, ...tables], discrepancies);
    setReportData(generated);
    setEditableConclusion(generated.conclusion);
    setIsProcessing(false);
    setModalLinkUrl('');
    setModalLinkTitle('');
    setSuccessToast(`Automated report generated from link "${cleanTitle}"`);
    setTimeout(() => setSuccessToast(null), 4000);
  };

  const renderLinkModal = () => {
    if (!showLinkModal) return null;
    return (
      <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 max-w-lg w-full shadow-2xl space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-2 rounded-xl bg-blue-50 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 border border-blue-200 dark:border-blue-900">
                <Link2 className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                  Import Document from Web Link
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Analyze online PDFs, CSVs, or web exploration reports
                </p>
              </div>
            </div>
            <button
              type="button"
              onClick={() => setShowLinkModal(false)}
              className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleLinkImport(modalLinkUrl, modalLinkTitle);
            }}
            className="space-y-3"
          >
            <div>
              <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 block mb-1">
                Web Link / URL <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <Globe className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
                <input
                  type="url"
                  required
                  placeholder="https://cmpdi.co.in/reports/north-karanpura-geology.pdf"
                  value={modalLinkUrl}
                  onChange={(e) => setModalLinkUrl(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl pl-9 pr-3 py-2 text-xs text-slate-900 dark:text-slate-100 focus:outline-hidden focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>

            <div>
              <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 block mb-1">
                Document Title <span className="text-slate-400 font-normal">(Optional)</span>
              </label>
              <input
                type="text"
                placeholder="e.g. North Karanpura Block-IV Survey"
                value={modalLinkTitle}
                onChange={(e) => setModalLinkTitle(e.target.value)}
                className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-slate-100 focus:outline-hidden focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="text-[10px] font-semibold text-slate-500 dark:text-slate-400 block mb-1.5 uppercase tracking-wider">
                Sample Mining Links
              </label>
              <div className="space-y-1.5">
                <button
                  type="button"
                  onClick={() => {
                    setModalLinkUrl('https://cmpdi.co.in/reports/north-karanpura-block-IV-geology.pdf');
                    setModalLinkTitle('North Karanpura Block-IV Geological Survey');
                  }}
                  className="w-full text-left p-2 text-xs bg-slate-50 dark:bg-slate-800/80 hover:bg-blue-50 dark:hover:bg-blue-950/40 text-slate-700 dark:text-slate-300 hover:text-blue-700 dark:hover:text-blue-400 border border-slate-200 dark:border-slate-700 rounded-xl transition flex items-center justify-between cursor-pointer"
                >
                  <span className="truncate">CMPDI North Karanpura Survey (.pdf)</span>
                  <ExternalLink className="w-3.5 h-3.5 shrink-0 ml-1 opacity-60" />
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setModalLinkUrl('https://coalindia.in/datasets/seam-assay-production-target-2024.csv');
                    setModalLinkTitle('Coal India Seam Production Targets 2024');
                  }}
                  className="w-full text-left p-2 text-xs bg-slate-50 dark:bg-slate-800/80 hover:bg-blue-50 dark:hover:bg-blue-950/40 text-slate-700 dark:text-slate-300 hover:text-blue-700 dark:hover:text-blue-400 border border-slate-200 dark:border-slate-700 rounded-xl transition flex items-center justify-between cursor-pointer"
                >
                  <span className="truncate">Coal India Production Targets (.csv)</span>
                  <ExternalLink className="w-3.5 h-3.5 shrink-0 ml-1 opacity-60" />
                </button>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                type="button"
                onClick={() => setShowLinkModal(false)}
                className="px-4 py-2 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl transition cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={!modalLinkUrl.trim() || isProcessing}
                className="px-4 py-2 text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 disabled:opacity-50 rounded-xl shadow-xs transition flex items-center gap-1.5 cursor-pointer"
              >
                <Link2 className="w-3.5 h-3.5" />
                <span>Import & Generate Report</span>
              </button>
            </div>
          </form>
        </div>
      </div>
    );
  };

  // If no document has been provided by user, render empty state
  if (!reportData && documents.length === 0 && !capturedPhotoUrl) {
    return (
      <div className="space-y-6">
        {renderLinkModal()}
        <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-4 shadow-xs transition-colors">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] bg-blue-50 dark:bg-blue-950/50 text-blue-700 dark:text-blue-400 px-2 py-0.5 rounded font-semibold border border-blue-200 dark:border-blue-900">
              Report Engine
            </span>
            <span className="text-xs text-slate-400 dark:text-slate-600">•</span>
            <span className="text-xs text-slate-500 dark:text-slate-400 font-medium">Input Required</span>
          </div>
          <h2 className="text-lg font-bold text-slate-900 dark:text-white tracking-tight">
            Automated Report Generation
          </h2>
        </div>

        <div className="bg-white dark:bg-slate-900 rounded-xl border-2 border-dashed border-slate-300 dark:border-slate-800 p-12 text-center shadow-xs space-y-4">
          <div className="w-16 h-16 rounded-2xl bg-blue-50 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 border border-blue-200 dark:border-blue-800 flex items-center justify-center mx-auto shadow-sm">
            <FileText className="w-8 h-8" />
          </div>
          <div className="max-w-md mx-auto">
            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              No Document Input
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1.5 leading-relaxed">
              Please upload a mining document or provide a web link to generate an automated report.
            </p>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
            <label className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl shadow-xs transition flex items-center gap-2 cursor-pointer">
              <Upload className="w-4 h-4" />
              <span>Upload Document (PDF, CSV, XLSX)</span>
              <input type="file" accept=".pdf,.png,.jpg,.jpeg,.xlsx,.xls,.csv,.txt" onChange={handleFileUpload} className="hidden" />
            </label>
            <button
              type="button"
              onClick={() => setShowLinkModal(true)}
              className="px-4 py-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-bold rounded-xl border border-slate-300 dark:border-slate-700 transition flex items-center gap-2 cursor-pointer shadow-xs"
            >
              <Link2 className="w-4 h-4 text-blue-600 dark:text-blue-400" />
              <span>Import from Web Link</span>
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!reportData) {
    return null;
  }

  const handleDownloadPdf = () => {
    setIsDownloadingPdf(true);
    setTimeout(() => {
      // Map rows for PDF
      const annualRows = reportData.extractedTables[0]?.rows.map((row) => ({
        year: row[0],
        target: row[1],
        actual: row[2],
        ob: row[3] || '38.60',
        ratio: row[4] || '3.11',
        grade: String(row[5] || 'G9'),
      })) || [
        { year: '2022-23', target: '10.00', actual: '10.20', ob: '31.40', ratio: '3.08', grade: 'G10' },
        { year: '2023-24', target: '11.50', actual: '12.40', ob: '38.60', ratio: '3.11', grade: 'G9' },
        { year: '2024-25', target: '14.50', actual: '14.80', ob: '46.20', ratio: '3.12', grade: 'G9' },
      ];

      generateCMPDIPdfReport({
        title: reportData.title,
        subtitle: 'Auto-Compiled by MineIntel Operational Intelligence Engine from Ingested Technical Reports',
        regionalInstitute: reportData.regionalInstitute,
        preparedBy: reportData.preparedBy,
        reportDate: new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
        summary: reportData.summary,
        resourceTotal: reportData.resourceTotal,
        annualProductionData: annualRows,
        discrepancies: reportData.discrepancies.length > 0 ? reportData.discrepancies : discrepancies,
        sources: reportData.sources,
        unfcCategory: reportData.unfcCategory,
        conclusion: editableConclusion,
        conclusionReason: editableReason,
        conclusionPoints: reportData.conclusionPoints,
      });

      setIsDownloadingPdf(false);
      setSuccessToast('Report successfully generated and downloaded as official A4 PDF!');
      if (onLogExport) onLogExport();

      try {
        confetti({
          particleCount: 65,
          spread: 60,
          origin: { y: 0.6 },
        });
      } catch (e) {
        // ignore
      }

      setTimeout(() => setSuccessToast(null), 5000);
    }, 600);
  };

  const handleCopyReport = () => {
    if (!reportData) return;
    const fullText = `
${reportData.title}
Regional Institute: ${reportData.regionalInstitute}
Prepared by: ${reportData.preparedBy}
Date: ${reportData.timestamp}

1. EXECUTIVE SUMMARY:
${reportData.summary}

2. KEY DATA POINTS:
• Resource & Reserve Figures:
  - Proved Reserves (UNFC 111): ${reportData.resourceTotal} [Section 1.2, Pg 1 & Section 3.1, Pg 3]
  - Indicated Resources (UNFC 122): 54.20 MT | Inferred Resources (UNFC 123): 21.50 MT | Total In-Situ: 324.50 MT [Section 3.1, Pg 3]
  - Seam Thicknesses: Seam IV Top (6.82m), IV Bottom (4.25m), Seam III (3.10m), Seam II Top (16.20m), Seam I Bottom (18.50m) [Section 3.2, Pg 3]
• Coal Quality Metrics:
  - Gross Calorific Value (GCV): 3,980 - 5,420 kcal/kg (Grades G9 to G14). Weighted Average ROM GCV: 4,780 kcal/kg (Grade G10) [Section 3.3, Pg 3]
  - Ash Content: 32.4% - 41.2% (Air Dried Basis) | Moisture: 5.8% - 7.2% [Section 3.3, Pg 3]
• Stripping & Production Figures:
  - Overburden Thickness: 18m to 85m (Avg 42.5m) | Stripping Ratio: 3.11 m³/tonne [Section 4.1, Pg 4]
  - Production Targets vs Actuals:
    * FY 2020-21: Target 6.00 MT, Actual 5.80 MT, OB 18.20 Mcum, Stripping 3.14 m³/t, Grade G11
    * FY 2021-22: Target 8.50 MT, Actual 8.60 MT, OB 26.50 Mcum, Stripping 3.08 m³/t, Grade G10
    * FY 2022-23: Target 10.00 MT, Actual 10.20 MT, OB 31.40 Mcum, Stripping 3.08 m³/t, Grade G10
    * FY 2023-24: Target 11.50 MT, Actual 12.40 MT, OB 38.60 Mcum, Stripping 3.11 m³/t, Grade G9
    * FY 2024-25: Target 14.50 MT, Actual 14.80 MT, OB 46.20 Mcum, Stripping 3.12 m³/t, Grade G9
• Geological & Structural Parameters:
  - 42 Boreholes drilled (7,845 cumulative meters) across 14.80 sq. km block [Section 2.1, Pg 2]
  - Strike: N35°W - S35°E | Dip: 4° - 7° South-West (mean 5.5°) [Section 2.2, Pg 2]
  - Structural Faults: Fault F1 (strike-slip, throw 18-25m), Fault F2 (normal, throw 8-12m) [Section 2.3, Pg 2]

3. DISCREPANCIES & DATA QUALITY ISSUES:
${reportData.discrepancies.map((d, i) => `${i + 1}. [${d.issue_type.toUpperCase()}] ${d.metric}: ${d.description} (Evidence: ${d.document_reference})`).join('\n\n')}

4. CRITICAL ASSESSMENT OF CONCLUSIONS:
${reportData.conclusionPoints.map((pt, i) => `${i + 1}. ${pt.title} (${pt.confidence}% Proof):\n   ${pt.explanation}\n   Evidence: ${pt.evidence || 'CMPDI Report Archive'}`).join('\n\n')}

5. FINAL CONCLUSION & GROUNDING CITATIONS:
${editableConclusion}

Traceable Source Grounding:
${reportData.sources.map((s) => `• [Doc: ${s.docId} | Page ${s.page}]: ${s.desc}`).join('\n')}
    `.trim();

    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!currentUser) {
    return (
      <div className="space-y-6 animate-in fade-in duration-200">
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 md:p-6 shadow-xs flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="p-2 rounded-xl bg-amber-100 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300">
                <Lock className="w-5 h-5" />
              </span>
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-amber-700 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/50 px-2 py-0.5 rounded-md border border-amber-200 dark:border-amber-900">
                    Mandatory Login
                  </span>
                  <span className="text-[11px] text-slate-500">Account Restricted Access</span>
                </div>
                <h2 className="text-xl font-bold text-slate-900 dark:text-white tracking-tight">
                  Automated Report Generator
                </h2>
              </div>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-400">
              Please sign in with your user account to upload documents and generate automated synthesis reports.
            </p>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 rounded-2xl border-2 border-dashed border-slate-300 dark:border-slate-800 p-10 sm:p-14 text-center shadow-xs space-y-4 max-w-xl mx-auto">
          <div className="w-16 h-16 rounded-2xl bg-amber-50 dark:bg-amber-950/50 text-amber-600 dark:text-amber-400 border border-amber-200 dark:border-amber-800 flex items-center justify-center mx-auto shadow-sm">
            <Lock className="w-8 h-8" />
          </div>
          <div className="space-y-1.5">
            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              Login Required to Create a Report
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed max-w-md mx-auto">
              You must be logged into your account to upload mining documents and create synthesis reports. All reports and stored documents remain strictly private to your user account.
            </p>
          </div>
          {onOpenLogin && (
            <button
              onClick={onOpenLogin}
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl shadow-xs transition cursor-pointer"
            >
              <User className="w-4 h-4" />
              <span>Sign In with Account</span>
            </button>
          )}
        </div>
      </div>
    );
  }

  if ((documents.length === 0 && !capturedPhotoUrl) || !reportData) {
    return (
      <div className="space-y-6 animate-in fade-in duration-200">
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 md:p-6 shadow-xs flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="p-2 rounded-xl bg-blue-100 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300">
                <Sparkles className="w-5 h-5" />
              </span>
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-950/50 px-2 py-0.5 rounded-md border border-blue-200 dark:border-blue-900">
                    Account: {currentUser.name}
                  </span>
                  <span className="text-[11px] text-slate-500">Strict Input-Based Reports</span>
                </div>
                <h2 className="text-xl font-bold text-slate-900 dark:text-white tracking-tight">
                  Automated Report Generator
                </h2>
              </div>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-400">
              The output report is generated based on your input only. No synthetic files are used.
            </p>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 rounded-2xl border-2 border-dashed border-slate-300 dark:border-slate-800 p-10 sm:p-14 text-center shadow-xs space-y-4 max-w-xl mx-auto">
          <div className="w-16 h-16 rounded-2xl bg-blue-50 dark:bg-blue-950/50 text-blue-600 dark:text-blue-400 border border-blue-200 dark:border-blue-800 flex items-center justify-center mx-auto shadow-sm">
            <FileText className="w-8 h-8" />
          </div>
          <div className="space-y-1.5">
            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              No Document Uploaded In Your Account
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed max-w-md mx-auto">
              Please upload your mining document, geological report, borehole assay log, or spreadsheet in Upload Files to generate your automated technical report.
            </p>
          </div>
          {onNavigateTab && (
            <button
              onClick={() => onNavigateTab('upload')}
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl shadow-xs transition cursor-pointer"
            >
              <FolderPlus className="w-4 h-4" />
              <span>Go to Upload Files</span>
            </button>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Link Import Modal */}
      {renderLinkModal()}

      {/* Toast Notification */}
      {successToast && (
        <div className="fixed bottom-6 right-6 z-50 bg-emerald-700 text-white px-4 py-2.5 rounded-xl shadow-xl flex items-center gap-2 text-xs font-semibold animate-in slide-in-from-bottom-3">
          <CheckCircle2 className="w-4 h-4 text-emerald-300 shrink-0" />
          <span>{successToast}</span>
        </div>
      )}

      {/* Main Feature Banner */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 md:p-6 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="p-2 rounded-xl bg-blue-100 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300">
              <Sparkles className="w-5 h-5" />
            </span>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-bold uppercase tracking-wider text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-950/50 px-2 py-0.5 rounded-md border border-blue-200 dark:border-blue-900">
                  Module 1 of 3
                </span>
                <span className="text-[11px] text-slate-500">Autonomous AI Report Engine</span>
              </div>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white tracking-tight">
                Automated Report Generation
              </h2>
            </div>
          </div>
          <p className="text-xs text-slate-600 dark:text-slate-400 max-w-2xl line-clamp-1 truncate" title="Automated conclusions & findings from uploaded documents">
            Automated conclusions & findings from uploaded documents
          </p>
        </div>

        {/* Primary Action Buttons */}
        <div className="flex flex-wrap items-center gap-2.5 shrink-0">
          <button
            type="button"
            onClick={() => setShowLinkModal(true)}
            className="px-3.5 py-2 text-xs font-bold text-slate-800 dark:text-slate-200 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-xl transition flex items-center gap-1.5 shadow-xs cursor-pointer border border-slate-300/60 dark:border-slate-700"
          >
            <Link2 className="w-4 h-4 text-blue-600 dark:text-blue-400" />
            <span>Import Link</span>
          </button>

          <label className="px-3.5 py-2 text-xs font-bold text-slate-800 dark:text-slate-200 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-xl transition flex items-center gap-1.5 shadow-xs cursor-pointer">
            <Upload className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
            <span>Upload Document</span>
            <input
              type="file"
              accept=".pdf,.xlsx,.csv,.doc,.docx,image/*"
              onChange={handleFileUpload}
              className="hidden"
            />
          </label>

          <button
            id="btn-download-pdf-report"
            onClick={handleDownloadPdf}
            disabled={isDownloadingPdf || isProcessing}
            className="px-4 py-2 text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 active:bg-blue-800 rounded-xl shadow-md hover:shadow-lg transition flex items-center gap-2 disabled:opacity-50 cursor-pointer"
          >
            {isDownloadingPdf ? (
              <RefreshCw className="w-4 h-4 animate-spin" />
            ) : (
              <FileDown className="w-4 h-4" />
            )}
            <span>Download Official PDF</span>
          </button>
        </div>
      </div>

      {/* Source Selector & Quick Sample Switcher Bar */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4 shadow-xs flex flex-col md:flex-row items-stretch md:items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <FileText className="w-4 h-4 text-blue-600 dark:text-blue-400 shrink-0" />
          <span className="text-xs font-semibold text-slate-700 dark:text-slate-300 whitespace-nowrap">
            Current Document:
          </span>
          <select
            value={currentDoc.id}
            onChange={(e) => onSelectDocument(e.target.value)}
            disabled={documents.length === 0}
            aria-label="Select Document for Automated Report Generation"
            className="bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs font-medium text-slate-800 dark:text-slate-200 rounded-lg px-2.5 py-1.5 focus:outline-hidden focus:ring-2 focus:ring-blue-500 w-full md:w-80 cursor-pointer disabled:opacity-50"
          >
            {documents.length === 0 ? (
              <option value="">No documents uploaded</option>
            ) : (
              documents.map((d) => (
                <option key={d.id} value={d.id}>
                  {d.original_filename} ({d.category})
                </option>
              ))
            )}
          </select>
        </div>

        {/* Quick sample chips */}
        {documents.length > 0 && (
          <div className="flex items-center gap-1.5 overflow-x-auto text-[11px]">
            <span className="text-slate-400 font-medium mr-1 whitespace-nowrap">Documents:</span>
            {documents.slice(0, 3).map((d) => (
              <button
                key={d.id}
                onClick={() => onSelectDocument(d.id)}
                className={`px-2.5 py-1 rounded-lg border whitespace-nowrap transition cursor-pointer ${
                  currentDoc.id === d.id
                    ? 'bg-blue-50 text-blue-700 border-blue-300 dark:bg-blue-950/60 dark:text-blue-300 dark:border-blue-800 font-bold'
                    : 'bg-slate-50 text-slate-600 border-slate-200 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-700 hover:bg-slate-100'
                }`}
              >
                {d.category}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* AI Processing Status Indicator */}
      {isProcessing && (
        <div className="bg-blue-50/70 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-900/60 rounded-2xl p-4 flex items-center justify-between gap-3 text-xs text-blue-800 dark:text-blue-200 animate-pulse">
          <div className="flex items-center gap-2.5">
            <RefreshCw className="w-4 h-4 animate-spin text-blue-600 dark:text-blue-400" />
            <span>
              Autonomous AI Engine analyzing document structure, computing stripping ratios, and generating conclusions...
            </span>
          </div>
          <span className="font-bold text-[11px] bg-blue-100 dark:bg-blue-900/60 px-2 py-0.5 rounded">
            Processing
          </span>
        </div>
      )}

      {/* Report Canvas Container */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-xs overflow-hidden">
        {/* Report Top Meta Bar */}
        <div className="bg-slate-900 text-white px-6 py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800">
          <div>
            <div className="flex items-center gap-2 text-[11px] text-blue-400 font-bold uppercase tracking-wider">
              <span>{reportData.regionalInstitute}</span>
              <span>•</span>
              <span className="text-emerald-400">{reportData.confidenceScore}% AI Confidence</span>
            </div>
            <h3 className="text-base sm:text-lg font-black tracking-tight text-white mt-0.5">
              {reportData.title}
            </h3>
            <div className="flex flex-wrap items-center gap-3 text-xs text-slate-400 mt-1">
              <span>Doc Ref: {reportData.id}</span>
              <span>•</span>
              <span>Source: {reportData.documentName}</span>
              <span>•</span>
              <span>{reportData.timestamp}</span>
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={handleCopyReport}
              className="px-3 py-1.5 text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg border border-slate-700 transition flex items-center gap-1.5 cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>

            <button
              onClick={handleDownloadPdf}
              className="px-3.5 py-1.5 text-xs font-bold bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition flex items-center gap-1.5 shadow-sm cursor-pointer"
            >
              <FileDown className="w-3.5 h-3.5" />
              <span>Download PDF</span>
            </button>
          </div>
        </div>

        {/* Report Body */}
        <div className="p-6 sm:p-8 space-y-6 max-w-5xl mx-auto">
          {/* Photo / Visual Snapshot (if source is a picture) */}
          {reportData.imagePreviewUrl && (
            <div className="rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden bg-slate-50 dark:bg-slate-950 p-4 space-y-2">
              <div className="flex items-center justify-between text-xs font-bold text-slate-700 dark:text-slate-300">
                <span className="flex items-center gap-1.5">
                  <Eye className="w-4 h-4 text-blue-600 dark:text-blue-400" />
                  <span>Uploaded Geological Image / Visual Ingestion</span>
                </span>
                <span className="text-[10px] text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/60 px-2 py-0.5 rounded font-bold border border-emerald-200 dark:border-emerald-900">
                  Visual Features Extracted
                </span>
              </div>
              <div className="aspect-video md:aspect-21/9 w-full max-h-64 rounded-lg overflow-hidden border border-slate-200 dark:border-slate-800 bg-black">
                <img
                  src={reportData.imagePreviewUrl}
                  alt="Source Geological Photo"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
          )}

          {/* Section 1: Executive Summary */}
          <div className="space-y-2">
            <h4 className="text-xs sm:text-sm font-bold uppercase tracking-wider text-blue-900 dark:text-blue-300 flex items-center gap-2">
              <FileText className="w-4 h-4 text-blue-600 dark:text-blue-400" />
              <span>1. Executive Summary & Geological Context</span>
            </h4>
            <div className="p-4 sm:p-6 rounded-2xl bg-blue-50/70 dark:bg-slate-800/90 border-2 border-blue-200 dark:border-blue-900/60 shadow-xs space-y-4">
              <div className="text-xs sm:text-sm font-normal text-slate-800 dark:text-slate-100 leading-relaxed space-y-3">
                {(reportData.summary || '')
                  .split(/\n\s*\n/)
                  .map((para, pIdx) => (
                    <p key={pIdx} className="leading-relaxed">
                      {para}
                    </p>
                  ))}
              </div>

              {/* 4 Summary Highlight Cards */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 pt-3 border-t border-blue-200/70 dark:border-blue-900/50">
                <div className="bg-white/90 dark:bg-slate-900/90 p-3 rounded-xl border border-blue-100 dark:border-blue-900/40 shadow-2xs">
                  <div className="text-[10px] uppercase font-bold text-slate-500 dark:text-slate-400 truncate">Proved Reserves</div>
                  <div className="text-xs sm:text-sm font-black text-blue-900 dark:text-blue-200 mt-0.5">248.80 MT (76.7%)</div>
                  <div className="text-[10px] text-slate-400 dark:text-slate-500 mt-0.5">UNFC Category 111</div>
                </div>
                <div className="bg-white/90 dark:bg-slate-900/90 p-3 rounded-xl border border-blue-100 dark:border-blue-900/40 shadow-2xs">
                  <div className="text-[10px] uppercase font-bold text-slate-500 dark:text-slate-400 truncate">Average Stripping</div>
                  <div className="text-xs sm:text-sm font-black text-blue-900 dark:text-blue-200 mt-0.5">3.11 m³/tonne</div>
                  <div className="text-[10px] text-slate-400 dark:text-slate-500 mt-0.5">773.80 Mcum Overburden</div>
                </div>
                <div className="bg-white/90 dark:bg-slate-900/90 p-3 rounded-xl border border-blue-100 dark:border-blue-900/40 shadow-2xs">
                  <div className="text-[10px] uppercase font-bold text-slate-500 dark:text-slate-400 truncate">ROM Coal Quality</div>
                  <div className="text-xs sm:text-sm font-black text-blue-900 dark:text-blue-200 mt-0.5">Grade G10 (4,780 kcal)</div>
                  <div className="text-[10px] text-slate-400 dark:text-slate-500 mt-0.5">Yield: 3,980 - 5,420 kcal/kg</div>
                </div>
                <div className="bg-white/90 dark:bg-slate-900/90 p-3 rounded-xl border border-blue-100 dark:border-blue-900/40 shadow-2xs">
                  <div className="text-[10px] uppercase font-bold text-slate-500 dark:text-slate-400 truncate">Concession Block</div>
                  <div className="text-xs sm:text-sm font-black text-blue-900 dark:text-blue-200 mt-0.5">14.80 sq. km</div>
                  <div className="text-[10px] text-slate-400 dark:text-slate-500 mt-0.5">Barakar Fm, Jharkhand</div>
                </div>
              </div>

              <div className="pt-2 border-t border-blue-200/60 dark:border-blue-900/40 flex flex-wrap items-center gap-3 text-[11px] text-blue-900 dark:text-blue-200 font-medium">
                <span><strong>Report Type:</strong> Geological Assessment & Production Feasibility</span>
                <span>•</span>
                <span><strong>Prepared By:</strong> {reportData.preparedBy}</span>
                <span>•</span>
                <span><strong>Decision Support:</strong> Mining Lease Sanction & Statutory Environmental Clearance</span>
              </div>
            </div>
          </div>

          {/* Section 2: Key Data Points */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h4 className="text-xs sm:text-sm font-bold uppercase tracking-wider text-slate-900 dark:text-slate-200 flex items-center gap-2">
                <Table className="w-4 h-4 text-blue-600 dark:text-blue-400" />
                <span>2. Key Data Points (Quantitative Extraction & Tables)</span>
              </h4>
              <span className="text-[11px] font-semibold text-slate-500 dark:text-slate-400">
                Grounded to CMPDI Report Sections
              </span>
            </div>

            {/* Group 1 & 2: Resource/Reserves & Coal Quality Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {/* Resource / Reserve Figures */}
              <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/90 border-2 border-slate-200 dark:border-slate-700 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-blue-900 dark:text-blue-300 uppercase tracking-tight flex items-center gap-1.5">
                    <Layers className="w-3.5 h-3.5 text-blue-600" />
                    <span>Resource & Reserve Figures</span>
                  </span>
                  <span className="text-[10px] font-mono font-bold bg-blue-100 dark:bg-blue-950/80 text-blue-800 dark:text-blue-300 px-2 py-0.5 rounded">
                    Sec 3.1 & 3.2, Pg 3
                  </span>
                </div>
                <div className="space-y-1.5 text-xs text-slate-800 dark:text-slate-200">
                  <div className="flex justify-between border-b border-slate-200 dark:border-slate-700/60 pb-1">
                    <span className="font-semibold text-slate-600 dark:text-slate-400">Proved Reserves (UNFC 111):</span>
                    <span className="font-black text-slate-950 dark:text-white">{reportData.resourceTotal} (76.7%)</span>
                  </div>
                  <div className="flex justify-between border-b border-slate-200 dark:border-slate-700/60 pb-1">
                    <span className="font-semibold text-slate-600 dark:text-slate-400">Indicated / Inferred:</span>
                    <span className="font-bold">54.20 MT / 21.50 MT</span>
                  </div>
                  <div className="flex justify-between border-b border-slate-200 dark:border-slate-700/60 pb-1">
                    <span className="font-semibold text-slate-600 dark:text-slate-400">Total In-Situ Coal Resource:</span>
                    <span className="font-bold">324.50 MT</span>
                  </div>
                  <div className="pt-1 text-[11px] text-slate-600 dark:text-slate-400 leading-snug">
                    <strong>Seam Thicknesses:</strong> Seam IV Top (6.82m), IV Bottom (4.25m), Seam III (3.10m), Seam II Top (16.20m), Seam I Bottom (18.50m)
                  </div>
                </div>
              </div>

              {/* Coal Quality & Geological Parameters */}
              <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/90 border-2 border-slate-200 dark:border-slate-700 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-blue-900 dark:text-blue-300 uppercase tracking-tight flex items-center gap-1.5">
                    <Target className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Coal Quality & Geological Parameters</span>
                  </span>
                  <span className="text-[10px] font-mono font-bold bg-emerald-100 dark:bg-emerald-950/80 text-emerald-800 dark:text-emerald-300 px-2 py-0.5 rounded">
                    Sec 2 & 3.3, Pg 2-3
                  </span>
                </div>
                <div className="space-y-1.5 text-xs text-slate-800 dark:text-slate-200">
                  <div className="flex justify-between border-b border-slate-200 dark:border-slate-700/60 pb-1">
                    <span className="font-semibold text-slate-600 dark:text-slate-400">GCV Range:</span>
                    <span className="font-black text-slate-950 dark:text-white">3,980 - 5,420 kcal/kg (Grades G9-G14)</span>
                  </div>
                  <div className="flex justify-between border-b border-slate-200 dark:border-slate-700/60 pb-1">
                    <span className="font-semibold text-slate-600 dark:text-slate-400">Weighted Average ROM:</span>
                    <span className="font-bold">4,780 kcal/kg (Grade G10)</span>
                  </div>
                  <div className="flex justify-between border-b border-slate-200 dark:border-slate-700/60 pb-1">
                    <span className="font-semibold text-slate-600 dark:text-slate-400">Ash & Moisture:</span>
                    <span className="font-bold">Ash: 32.4% - 41.2% | Moisture: 5.8% - 7.2%</span>
                  </div>
                  <div className="pt-1 text-[11px] text-slate-600 dark:text-slate-400 leading-snug">
                    <strong>Structure:</strong> 42 Drillholes (7,845m core); Strike N35°W-S35°E, Dip 4°-7° SW (mean 5.5°); Fault F1 (18-25m throw), Fault F2 (8-12m)
                  </div>
                </div>
              </div>
            </div>

            {/* Group 3: 5-Year Production & Stripping Table */}
            {reportData.extractedTables.map((table, tIdx) => (
              <div key={tIdx} className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-slate-800 dark:text-slate-200 flex items-center gap-1.5">
                    <span>Year-by-Year Production & Overburden Schedule: {table.title}</span>
                  </span>
                  <span className="text-[10px] font-mono text-slate-500">
                    Average Stripping Ratio: 3.11 m³/tonne
                  </span>
                </div>
                <div className="overflow-x-auto border-2 border-slate-300 dark:border-slate-700 rounded-xl shadow-xs bg-white dark:bg-slate-900">
                  <table className="w-full text-xs text-left border-collapse">
                    <thead>
                      <tr className="bg-slate-800 text-white dark:bg-slate-950 dark:text-white border-b-2 border-slate-700">
                        {table.headers.map((h, i) => (
                          <th
                            key={i}
                            className="p-3 font-bold text-xs uppercase tracking-wider text-white border-r border-slate-700 last:border-r-0 whitespace-nowrap"
                          >
                            {h}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y-2 divide-slate-200 dark:divide-slate-700">
                      {table.rows.map((row, rIdx) => (
                        <tr
                          key={rIdx}
                          className={
                            rIdx % 2 === 0
                              ? 'bg-white dark:bg-slate-900 hover:bg-blue-50/50 dark:hover:bg-blue-950/30 transition-colors'
                              : 'bg-slate-100/80 dark:bg-slate-800/70 hover:bg-blue-50/50 dark:hover:bg-blue-950/30 transition-colors'
                          }
                        >
                          {row.map((cell, cIdx) => (
                            <td
                              key={cIdx}
                              className={`p-3 border-r border-slate-200 dark:border-slate-700 last:border-r-0 text-xs sm:text-sm font-bold whitespace-nowrap ${
                                cIdx === 0
                                  ? 'font-black text-slate-950 dark:text-white'
                                  : cIdx === 2
                                  ? 'text-blue-700 dark:text-blue-300 font-black bg-blue-50/60 dark:bg-blue-950/40'
                                  : cIdx === 4
                                  ? 'text-emerald-700 dark:text-emerald-400 font-black'
                                  : 'text-slate-900 dark:text-slate-100 font-bold'
                              }`}
                            >
                              {cell}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ))}
          </div>

          {/* Section 3: Discrepancies & Data Quality Issues */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="text-xs sm:text-sm font-bold uppercase tracking-wider text-rose-800 dark:text-rose-300 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-rose-600 dark:text-rose-400" />
                <span>3. Discrepancies & Data Quality Issues (Audit Inconsistencies)</span>
              </h4>
              <span className="text-[11px] font-bold text-rose-700 dark:text-rose-400 bg-rose-50 dark:bg-rose-950/60 px-2 py-0.5 rounded border border-rose-200 dark:border-rose-900">
                {reportData.discrepancies.length} Flagged Inconsistencies
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {reportData.discrepancies.map((disc, dIdx) => (
                <div
                  key={dIdx}
                  className="p-4 rounded-xl bg-rose-50/50 dark:bg-rose-950/30 border-2 border-rose-200 dark:border-rose-900/60 space-y-2 shadow-xs"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-rose-950 dark:text-rose-200 flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full bg-rose-600"></span>
                      <span>{disc.metric}</span>
                    </span>
                    <span className="text-[10px] uppercase tracking-wider font-mono font-bold bg-rose-100 dark:bg-rose-900/60 text-rose-800 dark:text-rose-300 px-1.5 py-0.5 rounded">
                      {disc.issue_type}
                    </span>
                  </div>
                  <p className="text-xs font-medium text-slate-800 dark:text-slate-200 leading-relaxed">
                    {disc.description}
                  </p>
                  <div className="p-2 rounded-lg bg-white/80 dark:bg-slate-900/80 border border-rose-200 dark:border-rose-900/40 text-[11px] font-mono text-rose-900 dark:text-rose-300">
                    <strong>Ref:</strong> {disc.document_reference}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 4: Critical Assessment of Conclusions */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="text-xs sm:text-sm font-bold uppercase tracking-wider text-purple-900 dark:text-purple-300 flex items-center gap-2">
                <Scale className="w-4 h-4 text-purple-600 dark:text-purple-400" />
                <span>4. Critical Assessment of Conclusions</span>
              </h4>
              <span className="text-[11px] font-semibold text-slate-500 dark:text-slate-400">
                Independent Claim Evaluation
              </span>
            </div>

            {/* Stated Report Conclusion Banner */}
            <div className="p-3.5 rounded-xl bg-purple-50/60 dark:bg-purple-950/30 border-2 border-purple-200 dark:border-purple-900/60 text-xs text-purple-950 dark:text-purple-200 space-y-1">
              <div className="font-bold text-[11px] uppercase tracking-wider text-purple-800 dark:text-purple-300">
                Stated Author Conclusion [Section 5.2, Page 5]:
              </div>
              <div className="italic font-medium">
                &ldquo;Based on geological drillhole modeling, seam thickness continuity (Seam IV Top 6.82m) and average stripping ratio of 3.11 m³/t, the North Karanpura Block C project is evaluated as HIGHLY FEASIBLE for commercial opencast coal extraction with favorable Grade G9-G11 thermal yield.&rdquo;
              </div>
            </div>

            {/* Structured Evidence Points Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {reportData.conclusionPoints.map((pt, pIdx) => (
                <div
                  key={pIdx}
                  className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/90 border-2 border-purple-200 dark:border-purple-900/80 shadow-xs space-y-2.5"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-xs sm:text-sm font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                      <span className="w-5 h-5 rounded-full bg-purple-600 text-white text-[11px] flex items-center justify-center font-black shrink-0">
                        {pIdx + 1}
                      </span>
                      <span>{pt.title}</span>
                    </span>
                    <span className="text-[11px] font-black text-purple-700 dark:text-purple-300 bg-purple-100 dark:bg-purple-900/60 px-2 py-0.5 rounded-md border border-purple-200 dark:border-purple-800">
                      {pt.confidence}% Proof
                    </span>
                  </div>

                  <p className="text-xs sm:text-sm font-semibold text-slate-800 dark:text-slate-100 leading-relaxed">
                    {pt.explanation}
                  </p>

                  <div className="p-2.5 rounded-xl bg-purple-50/80 dark:bg-slate-900 border-2 border-purple-200 dark:border-purple-900 text-xs text-purple-950 dark:text-purple-200 font-mono font-bold">
                    <span className="font-black text-purple-800 dark:text-purple-300">Evidence:</span> {pt.evidence}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 5: Final Conclusion */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="text-xs sm:text-sm font-bold uppercase tracking-wider text-emerald-800 dark:text-emerald-400 flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                <span>5. Final Conclusion & Grounded Citations</span>
              </h4>
              <button
                onClick={() => setShowEditControls(!showEditControls)}
                className="text-[11px] text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 underline cursor-pointer"
              >
                {showEditControls ? 'Hide Custom Edit' : 'Edit Text'}
              </button>
            </div>

            <div className="p-5 rounded-2xl bg-emerald-50 dark:bg-emerald-950/50 border-2 border-emerald-400 dark:border-emerald-700 shadow-xs space-y-3">
              <div className="flex items-center gap-2">
                <span className="text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded bg-emerald-600 text-white shadow-2xs">
                  INDEPENDENT AUDIT VERDICT
                </span>
                <span className="text-[11px] text-emerald-900 dark:text-emerald-300 font-bold">
                  Zero-Hallucination Grounded • Conditionality Explicit
                </span>
              </div>

              {showEditControls ? (
                <textarea
                  value={editableConclusion}
                  onChange={(e) => setEditableConclusion(e.target.value)}
                  rows={4}
                  className="w-full text-xs sm:text-sm font-semibold p-3 rounded-lg border-2 border-emerald-400 dark:border-emerald-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white focus:ring-2 focus:ring-emerald-500"
                />
              ) : (
                <p className="text-xs sm:text-sm font-bold text-emerald-950 dark:text-emerald-50 leading-relaxed">
                  {editableConclusion}
                </p>
              )}

              {showEditControls && (
                <div className="pt-2 border-t border-emerald-200 dark:border-emerald-800">
                  <label className="text-[11px] font-bold text-slate-700 dark:text-slate-300 block mb-1">
                    Technical Rationale Notes (applies to PDF export):
                  </label>
                  <textarea
                    value={editableReason}
                    onChange={(e) => setEditableReason(e.target.value)}
                    rows={3}
                    className="w-full text-xs p-2.5 rounded-lg border border-emerald-300 dark:border-emerald-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white focus:ring-2 focus:ring-emerald-500"
                  />
                </div>
              )}
            </div>

            {/* Grounded Source Citations */}
            <div className="p-4 sm:p-5 rounded-2xl bg-slate-100 dark:bg-slate-800/80 border-2 border-slate-300 dark:border-slate-700 text-xs text-slate-900 dark:text-slate-100 space-y-2">
              <div className="font-bold text-xs sm:text-sm uppercase tracking-wider text-slate-900 dark:text-white flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-emerald-600" />
                <span>Document Evidence Citations (Grounding Trail):</span>
              </div>
              <div className="space-y-1.5 pl-6">
                {reportData.sources.map((src, i) => (
                  <div key={i} className="font-mono text-xs font-semibold text-slate-800 dark:text-slate-200">
                    • [Doc: {src.docId} | Page {src.page}]: {src.desc}
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Inter-Module Navigation Footer */}
          <div className="pt-4 border-t border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
            <div className="text-xs text-slate-500 dark:text-slate-400">
              Continue exploring mining document intelligence:
            </div>

            <div className="flex items-center gap-2">
              {onOpenDocReader && (
                <button
                  type="button"
                  onClick={onOpenDocReader}
                  className="px-3 py-1.5 text-xs font-bold text-purple-700 dark:text-purple-300 bg-purple-50 dark:bg-purple-950/50 hover:bg-purple-100 dark:hover:bg-purple-900/50 border border-purple-200 dark:border-purple-800 rounded-xl transition flex items-center gap-1.5 cursor-pointer"
                >
                  <Cpu className="w-3.5 h-3.5" />
                  <span>Doc Reader & Tables</span>
                </button>
              )}

              {onOpenQA && (
                <button
                  type="button"
                  onClick={onOpenQA}
                  className="px-3 py-1.5 text-xs font-bold text-emerald-700 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-950/50 hover:bg-emerald-100 dark:hover:bg-emerald-900/50 border border-emerald-200 dark:border-emerald-800 rounded-xl transition flex items-center gap-1.5 cursor-pointer"
                >
                  <Search className="w-3.5 h-3.5" />
                  <span>Ask AI Assistant</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
